# Generated by Django 5.0.4 on 2024-12-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author_first", models.CharField(max_length=60)),
                ("author_last", models.CharField(max_length=60)),
                ("fiction", models.BooleanField(default=False)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("VG", "Very Good"),
                            ("G", "Good"),
                            ("U", "Used"),
                            ("NR", "Needs Repair"),
                        ],
                        default="G",
                        max_length=2,
                    ),
                ),
                ("assunta_read", models.BooleanField(default=False)),
                ("lucian_read", models.BooleanField(default=False)),
            ],
        ),
    ]
